package com.mco.wackyguesses.entities.cloud;

import net.ilexiconn.llibrary.client.model.ModelAnimator;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelBase;
import net.ilexiconn.llibrary.client.model.tools.AdvancedModelRenderer;
import net.ilexiconn.llibrary.server.animation.IAnimatedEntity;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelCloud extends AdvancedModelBase {
    public AdvancedModelRenderer BodyA;
    public AdvancedModelRenderer RFrontLeg;
    public AdvancedModelRenderer RBackLeg;
    public AdvancedModelRenderer LBackLeg;
    public AdvancedModelRenderer TailA;
    public AdvancedModelRenderer HeadA;
    public AdvancedModelRenderer RChubA;
    public AdvancedModelRenderer BackChub;
    public AdvancedModelRenderer FrontChub;
    public AdvancedModelRenderer TopChubA;
    public AdvancedModelRenderer LChubA;
    public AdvancedModelRenderer BottomChubA;
    public AdvancedModelRenderer LFrontLeg;
    public AdvancedModelRenderer PoofA;
    public AdvancedModelRenderer PoofB;
    public AdvancedModelRenderer PoofD;
    public AdvancedModelRenderer PoofE;
    public AdvancedModelRenderer TailB;
    public AdvancedModelRenderer Nose;
    public AdvancedModelRenderer LEar;
    public AdvancedModelRenderer REar;
    public AdvancedModelRenderer RCheek;
    public AdvancedModelRenderer LCheek;
    public AdvancedModelRenderer Chin;
    public AdvancedModelRenderer RChubB;
    public AdvancedModelRenderer RChubC;
    public AdvancedModelRenderer TopChubB;
    public AdvancedModelRenderer TopChubC;
    public AdvancedModelRenderer LChubB;
    public AdvancedModelRenderer LChubC;
    public AdvancedModelRenderer BottomChubB;
    public AdvancedModelRenderer PoofC;
    private ModelAnimator animator;

    public ModelCloud() {
        this.textureWidth = 128;
        this.textureHeight = 128;
        this.RChubA = new AdvancedModelRenderer(this, 28, 38);
        this.RChubA.setRotationPoint(2.5F, 3.5F, -7.5F);
        this.RChubA.addBox(0.0F, 0.0F, 0.0F, 1, 5, 15, 0.0F);
        this.BottomChubB = new AdvancedModelRenderer(this, 16, 18);
        this.BottomChubB.setRotationPoint(0.3F, 0.5F, 1.0F);
        this.BottomChubB.addBox(0.0F, 1.0F, 1.0F, 1, 3, 12, 0.0F);
        this.PoofA = new AdvancedModelRenderer(this, 0, 65);
        this.PoofA.setRotationPoint(0.0F, 4.0F, 0.0F);
        this.PoofA.addBox(-5.0F, -4.0F, -7.0F, 10, 9, 14, 0.0F);
        this.TailB = new AdvancedModelRenderer(this, 4, 15);
        this.TailB.setRotationPoint(0.0F, 8.0F, 0.0F);
        this.TailB.addBox(-0.5F, 0.0F, 0.0F, 1, 8, 1, 0.0F);
        this.setRotateAngle(this.TailB, 0.95609134F, 0.0F, 0.0F);
        this.RChubC = new AdvancedModelRenderer(this, 16, 18);
        this.RChubC.setRotationPoint(0.3F, 0.5F, 1.0F);
        this.RChubC.addBox(0.0F, 1.0F, 1.0F, 1, 3, 12, 0.0F);
        this.TopChubB = new AdvancedModelRenderer(this, 29, 20);
        this.TopChubB.setRotationPoint(0.3F, -0.5F, -0.5F);
        this.TopChubB.addBox(0.0F, 1.0F, 1.0F, 1, 4, 14, 0.0F);
        this.TailA = new AdvancedModelRenderer(this, 0, 15);
        this.TailA.setRotationPoint(0.0F, 6.0F, 7.0F);
        this.TailA.addBox(-0.5F, 0.0F, 0.0F, 1, 8, 1, 0.0F);
        this.setRotateAngle(this.TailA, 0.9000663F, 0.0F, 0.0F);
        this.BottomChubA = new AdvancedModelRenderer(this, 29, 20);
        this.BottomChubA.setRotationPoint(3.0F, 8.5F, -8.0F);
        this.BottomChubA.addBox(0.0F, 1.0F, 1.1F, 1, 4, 14, 0.0F);
        this.setRotateAngle(this.BottomChubA, 0.0F, 0.0F, 1.5707964F);
        this.TopChubC = new AdvancedModelRenderer(this, 16, 18);
        this.TopChubC.setRotationPoint(0.3F, 0.5F, 1.0F);
        this.TopChubC.addBox(0.0F, 1.0F, 1.0F, 1, 3, 12, 0.0F);
        this.Chin = new AdvancedModelRenderer(this, 0, 39);
        this.Chin.setRotationPoint(1.0F, 1.4F, -2.0F);
        this.Chin.addBox(-3.0F, 0.0F, -2.0F, 4, 1, 3, 0.0F);
        this.RCheek = new AdvancedModelRenderer(this, 0, 27);
        this.RCheek.setRotationPoint(1.8F, 1.0F, -4.0F);
        this.RCheek.addBox(0.0F, -2.0F, 0.0F, 1, 2, 3, 0.0F);
        this.PoofB = new AdvancedModelRenderer(this, 4, 65);
        this.PoofB.setRotationPoint(0.0F, -1.0F, 0.0F);
        this.PoofB.addBox(-4.0F, 0.0F, -6.0F, 8, 1, 12, 0.0F);
        this.RChubB = new AdvancedModelRenderer(this, 29, 20);
        this.RChubB.setRotationPoint(0.3F, -0.5F, -0.5F);
        this.RChubB.addBox(0.0F, 1.0F, 1.0F, 1, 4, 14, 0.0F);
        this.PoofC = new AdvancedModelRenderer(this, 8, 65);
        this.PoofC.setRotationPoint(-1.0F, -1.0F, 1.0F);
        this.PoofC.addBox(-2.0F, 0.0F, -6.0F, 6, 1, 10, 0.0F);
        this.TopChubA = new AdvancedModelRenderer(this, 28, 38);
        this.TopChubA.setRotationPoint(-2.5F, 3.5F, -7.5F);
        this.TopChubA.addBox(0.0F, 0.0F, 0.0F, 1, 5, 15, 0.0F);
        this.setRotateAngle(this.TopChubA, 0.0F, 0.0F, -1.5707964F);
        this.RFrontLeg = new AdvancedModelRenderer(this, 40, 0);
        this.RFrontLeg.setRotationPoint(1.2F, 7.0F, -5.0F);
        this.RFrontLeg.addBox(-1.0F, 0.0F, -1.0F, 2, 6, 2, 0.0F);
        this.setRotateAngle(this.RFrontLeg, -0.00951134F, 0.0F, 0.0F);
        this.LChubC = new AdvancedModelRenderer(this, 16, 18);
        this.LChubC.setRotationPoint(0.3F, 0.5F, 1.0F);
        this.LChubC.addBox(0.0F, 1.0F, 1.0F, 1, 3, 12, 0.0F);
        this.FrontChub = new AdvancedModelRenderer(this, 0, 33);
        this.FrontChub.setRotationPoint(-2.0F, 4.0F, -8.5F);
        this.FrontChub.addBox(0.0F, 0.0F, 0.0F, 4, 4, 1, 0.0F);
        this.LEar = new AdvancedModelRenderer(this, 0, 10);
        this.LEar.setRotationPoint(0.0F, 0.0F, -2.0F);
        this.LEar.addBox(-2.0F, -3.0F, 0.0F, 1, 1, 2, 0.0F);
        this.PoofE = new AdvancedModelRenderer(this, 0, 73);
        this.PoofE.setRotationPoint(-7.0F, 0.0F, 6.0F);
        this.PoofE.addBox(0.0F, 2.0F, -11.0F, 14, 5, 10, 0.0F);
        this.REar = new AdvancedModelRenderer(this, 6, 10);
        this.REar.setRotationPoint(0.0F, 0.0F, -2.0F);
        this.REar.addBox(1.0F, -3.0F, 0.0F, 1, 1, 2, 0.0F);
        this.BackChub = new AdvancedModelRenderer(this, 0, 33);
        this.BackChub.setRotationPoint(1.0F, 4.0F, 8.0F);
        this.BackChub.addBox(-3.0F, 0.0F, -0.5F, 4, 4, 1, 0.0F);
        this.LFrontLeg = new AdvancedModelRenderer(this, 40, 0);
        this.LFrontLeg.setRotationPoint(-1.2F, 7.0F, -5.0F);
        this.LFrontLeg.addBox(-1.0F, 0.0F, -1.0F, 2, 6, 2, 0.0F);
        this.Nose = new AdvancedModelRenderer(this, 0, 24);
        this.Nose.setRotationPoint(0.0F, 0.0F, 0.0F);
        this.Nose.addBox(-1.5F, 0.0F, -4.0F, 3, 2, 1, 0.0F);
        this.RBackLeg = new AdvancedModelRenderer(this, 8, 13);
        this.RBackLeg.setRotationPoint(1.1F, 7.0F, 6.0F);
        this.RBackLeg.addBox(-1.0F, 0.0F, -1.0F, 2, 6, 2, 0.0F);
        this.LBackLeg = new AdvancedModelRenderer(this, 8, 13);
        this.LBackLeg.setRotationPoint(-1.1F, 7.0F, 6.0F);
        this.LBackLeg.addBox(-1.0F, 0.0F, -1.0F, 2, 6, 2, 0.0F);
        this.HeadA = new AdvancedModelRenderer(this, 0, 0);
        this.HeadA.setRotationPoint(0.0F, 3.0F, -8.0F);
        this.HeadA.addBox(-2.5F, -2.0F, -5.0F, 5, 4, 5, 0.0F);
        this.LCheek = new AdvancedModelRenderer(this, 0, 27);
        this.LCheek.setRotationPoint(-2.8F, 1.0F, -4.0F);
        this.LCheek.addBox(0.0F, -2.0F, 0.0F, 1, 2, 3, 0.0F);
        this.LChubB = new AdvancedModelRenderer(this, 29, 20);
        this.LChubB.setRotationPoint(0.3F, -0.5F, -0.5F);
        this.LChubB.addBox(0.0F, 1.0F, 1.0F, 1, 4, 14, 0.0F);
        this.PoofD = new AdvancedModelRenderer(this, 0, 69);
        this.PoofD.setRotationPoint(-6.0F, 1.0F, 5.0F);
        this.PoofD.addBox(0.0F, 0.0F, -11.0F, 12, 7, 12, 0.0F);
        this.BodyA = new AdvancedModelRenderer(this, 0, 42);
        this.BodyA.setRotationPoint(0.0F, 11.0F, 1.0F);
        this.BodyA.addBox(-3.0F, 3.0F, -8.0F, 6, 6, 16, 0.0F);
        this.LChubA = new AdvancedModelRenderer(this, 28, 38);
        this.LChubA.setRotationPoint(-2.5F, 8.5F, -7.5F);
        this.LChubA.addBox(0.0F, 0.0F, 0.0F, 1, 5, 15, 0.0F);
        this.setRotateAngle(this.LChubA, 0.0F, 0.0F, -3.1415927F);
        this.BodyA.addChild(this.RChubA);
        this.BottomChubA.addChild(this.BottomChubB);
        this.BodyA.addChild(this.PoofA);
        this.TailA.addChild(this.TailB);
        this.RChubB.addChild(this.RChubC);
        this.TopChubA.addChild(this.TopChubB);
        this.BodyA.addChild(this.TailA);
        this.BodyA.addChild(this.BottomChubA);
        this.TopChubB.addChild(this.TopChubC);
        this.HeadA.addChild(this.Chin);
        this.HeadA.addChild(this.RCheek);
        this.BodyA.addChild(this.PoofB);
        this.RChubA.addChild(this.RChubB);
        this.PoofB.addChild(this.PoofC);
        this.BodyA.addChild(this.TopChubA);
        this.BodyA.addChild(this.RFrontLeg);
        this.LChubB.addChild(this.LChubC);
        this.BodyA.addChild(this.FrontChub);
        this.HeadA.addChild(this.LEar);
        this.BodyA.addChild(this.PoofE);
        this.HeadA.addChild(this.REar);
        this.BodyA.addChild(this.BackChub);
        this.BodyA.addChild(this.LFrontLeg);
        this.HeadA.addChild(this.Nose);
        this.BodyA.addChild(this.RBackLeg);
        this.BodyA.addChild(this.LBackLeg);
        this.BodyA.addChild(this.HeadA);
        this.HeadA.addChild(this.LCheek);
        this.LChubA.addChild(this.LChubB);
        this.BodyA.addChild(this.PoofD);
        this.BodyA.addChild(this.LChubA);
        this.animator = ModelAnimator.create();
        this.updateDefaultPose();
    }

    @Override
    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntityCloud cloud = (EntityCloud)entity;
        this.setRotationAngles(f,f1,f2,f3,f4,f5, entity);
        this.animate(cloud, f, f1, f2, f3, f4, f5);
        this.BodyA.render(f5);
    }

    public void setRotateAngle(AdvancedModelRenderer AdvancedModelRenderer, float x, float y, float z) {
        AdvancedModelRenderer.rotateAngleX = x;
        AdvancedModelRenderer.rotateAngleY = y;
        AdvancedModelRenderer.rotateAngleZ = z;
    }

    public void animate(IAnimatedEntity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        EntityCloud cloud = (EntityCloud)entity;
        this.animator.update(cloud);
        this.setRotationAngles(f, f1, f2, f3, f4, f5, cloud);
        this.animator.setAnimation(EntityCloud.ANIMATION_HOVER);
        this.animator.startKeyframe(40);
        this.animator.move(this.BodyA, 0.0F, -20.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(20);
        this.animator.resetKeyframe(1);
        this.animator.setAnimation(EntityCloud.ANIMATION_STAND);
        this.animator.startKeyframe(10);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, 0.0F, 0.0F, 0.5F);
        this.animator.rotate(this.RFrontLeg, 0.0F, 0.0F, -0.5F);
        this.animator.endKeyframe();
        this.animator.setStaticKeyframe(10);
        this.animator.startKeyframe(3);
        this.animator.rotate(this.HeadA, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RFrontLeg, 0.5F, 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.rotate(this.HeadA, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RFrontLeg, -0.5F, 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.rotate(this.HeadA, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RFrontLeg, 0.5F, 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.rotate(this.HeadA, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RFrontLeg, -0.5F, 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.rotate(this.HeadA, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, -0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RFrontLeg, 0.5F, 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.startKeyframe(3);
        this.animator.rotate(this.HeadA, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.RBackLeg, 1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.BodyA, -1.0F, 0.0F, 0.0F);
        this.animator.rotate(this.LFrontLeg, 0.5F, 0.0F, 0.0F);
        this.animator.rotate(this.RFrontLeg, -0.5F, 0.0F, 0.0F);
        this.animator.endKeyframe();
        this.animator.resetKeyframe(1);
    }

    @Override
    public void setRotationAngles(float limbSwing, float limbSwingAmount, float ageInTicks, float netHeadYaw, float headPitch, float scaleFactor, Entity entityIn) {
        super.setRotationAngles(limbSwing, limbSwingAmount, ageInTicks, netHeadYaw, headPitch, scaleFactor, entityIn);
        this.resetToDefaultPose();
        this.HeadA.rotateAngleY = netHeadYaw * 0.017453292F;
        this.HeadA.rotateAngleX = headPitch * 0.017453292F;
        this.RFrontLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
        this.LFrontLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + 3.1415927F) * 1.4F * limbSwingAmount;
        this.RBackLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F + 3.1415927F) * 1.4F * limbSwingAmount;
        this.LBackLeg.rotateAngleX = MathHelper.cos(limbSwing * 0.6662F) * 1.4F * limbSwingAmount;
    }
}